### ISSUE TITLE
Give feedback on failure

### ISSUE THREAD

**Issue by shkm** [shkm/vssh#2]
Just spent 15 minutes wondering why vssh wasn't working, when it turns out a port changed and I needed to `--refresh`. We run ssh with `-q` (quiet mode) so we don't get any feedback when stuff like this happens.

**Comment by lawrence-berry** [comment]
So `vssh` worked for me on first install, but stopped working later that day, no feedback just drops me back to my (Bash) shell. My co-worker also installed it & got that result straight out the box, would be great if we could get some error messages as to why it's failing as it solves a couple of different issues with Vagrant I've been meaning to find a solution for.

**Comment by shkm** [comment]
Definitely going to be adding some feedback!

I'm curious as to why your co-worker had that result straight off the bat, @lawrence-berry. Is there anything particularly odd about the vagrant setup?

**Comment by strzibny** [comment]
What about invoking `--refresh` automatically after some timeout?

**Comment by shkm** [comment]
I'd considered that, @strzibny, but I don't think we need to refresh unless we generally need to change something unless something changes in the config. Unless you can think of other reasons?

**Comment by shkm** [comment]
OK: d9d037018f2b998a8ef67ddd4f55e3be1e27c555

No custom errors, but it will show ssh errors. If you see an error, make sure your box is running and run `--refresh`.
