### ISSUE TITLE
Automatically refresh after box start

### ISSUE THREAD

**Issue by martijn** [shkm/vssh#5]
I often have multiple boxes running simultaneously, which causes SSH ports to change for a single box. When the port changes the vssh config becomes invalid. It would be nice if vssh could refresh automatically after a box restart. I don't really see a way of implementing this, yet, tough.

**Comment by shkm** [comment]
Considering implementing this as an "on-fail" hook or something, settable in the config. If ssh fails for whatever reason, run a command (e.g. `vagrant --refresh`).

**Comment by shkm** [comment]
Added in 3.0
